services:
  app:
    # BackEnd Service
    build:
      context: .
    container_name: app-container
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - mysql
    volumes:
      - ./src:/app/src
    networks:
      - backend

  mysql:
    # MySQL Database Service
    image: mysql:8.3
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: new_db
    volumes:
      - mysql_data:/var/lib/mysql
    # logging:
    #   driver: "none"
    networks:
      - backend

  adminer:
    # Adminer UI for DB
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    # logging:
    #   driver: "none"
    networks:
      - backend

volumes:
  mysql_data:


networks:
  backend:
    driver: bridge
